### PR TITLE
fix(docz-utils): fix closing tag detection in `removeTags`

### LINKED ISSUE #1691: SyntaxError: Expected corresponding JSX closing tag
Getting `SyntaxError: Expected corresponding JSX closing tag` error when using any component with children inside the `Playground` component.

Using components that self close, for example `<MyComponent />` works fine.

Here is a sample with the error. Please click on Components > Alert on the left menu.

https://codesandbox.io/s/docz-example-xj522

Thanks

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
### Description

I wrote the description of this fix and the reason behind it at https://github.com/doczjs/docz/issues/1691#issuecomment-1025928444.

I fixed it in different commits:
- `test(docz-utils): add test for current removeTags behavior` shows the old behavior (one test was correct, the other one was already broken)
- `chore(docz-utils): update @babel/* dependencies` updates `@babel/traverse` and the other babel packages, to force the version containing the fix for the bug docz was relying on
- `test(docz-utils): update removeTags (broken) snapshots` updates the tests to show the new broken behavior
- `fix(docz-utils): fix closing tag detection in removeTags` fixes both the broken tests

Fixes #1691

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

**Review by adbayb — APPROVED** [review]
Thank you @nicolo-ribaudo . 
It seems to work properly 🎉 (tested in my project via [patch-package](https://github.com/ds300/patch-package)).

File: core/docz-utils/src/jsx.ts [hunk 1]
```diff
@@ -2,19 +2,29 @@ import * as jsxUtils from 'jsx-ast-utils'
...
-export const removeTags = (code: string) => {
-  const open = codeFromNode(p => p.isJSXOpeningElement())
-  const close = codeFromNode(p => p.isJSXClosingElement())
+const getTagContentsRange = valueFromTraverse<[number, number] | null>(
+  p => p.isJSXElement(),
+  ({ node }) => {
+    if (!node.closingElement) {
+      // if the JSX element doesn't have a closingElement, it's because it's self-closed
+      // and thus does not have any content: <Playground />
+      return null
```
Comment (renatobenks) [inline core/docz-utils/src/jsx.ts:19]: what about returning `[0, 0]` as the default value?

File: core/docz-utils/.babelrc [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+    [
+      "@babel/preset-env",
+      {
+        "targets": {
+          "node": "current"
+        }
+      }
+    ]
+  ]
+}
```
Comment (renatobenks) [inline core/docz-utils/.babelrc:14]: why did you have to add it? it shouldn't be needed

**Comment by renatobenks** [comment]
Great job at this @nicolo-ribaudo 🎉

File: core/docz-utils/src/jsx.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply core/docz-utils/src/jsx.ts:19]: With invalid inputs (i.e. if it can't find a JSX element) the function returned by `valueFromTraverse` returns an empty string, so we still need the default value fallback when calling `getTagContentsRange` on line 26.
- I don't think this will happen in practice, but it's better to be safe and avoid crashing
- Otherwise Typescript complaints

Since we need the default value there anyway, returning something "falsy" here allows us to specify the default value only once.

File: core/docz-utils/.babelrc (hunk 2 above)
Comment (nicolo-ribaudo) [reply core/docz-utils/.babelrc:14]: Without this Jest was crashing on the TS syntax: it was not configured yet just because this package didn't have any tests. I copied it from other packages in this repo which already had some tests.

**Comment by Elgeneinar** [comment]
Any estimate on when this will be completed?

File: core/docz-utils/.babelrc (hunk 2 above)
Comment (renatobenks) [reply core/docz-utils/.babelrc:14]: I thought that probably it would be the reason, but thanks for explaining

File: core/docz-utils/src/jsx.ts (hunk 1 above)
Comment (renatobenks) [reply core/docz-utils/src/jsx.ts:19]: interesting to know that, it's fair enough! well done btw

**Review by renatobenks — APPROVED** [review]

**Comment by renatobenks** [comment]
@Elgeneinar I'm scheduling the release to be done between today and tomorrow, but I'll try to let everyone knows in all following corresponded PRs
